### ISSUE TITLE
Utilize the WordPress 'Remember Me'

### ISSUE THREAD

**Issue by tarecord** [NorthStarMarketing/sign-in-with-google#59]
Original request: https://wordpress.org/support/topic/remember-me-option-4/

>Hello,
>
>Would it be possible to pass on the “Remember Me” paramater to the plug-in? I patched it for now, it is really super simple.
>
>Thanks

**Comment by tarecord** [comment]
I don't think we actually need to handle this since Google should be responsible for keeping the user signed in. We're just sending them over and logging in the user once they're authenticated.

After thinking about it more, further separating the button away from the login form would make a lot more sense in the long run—to really add visual separation between the two methods of authenticating.

<img width="474" alt="Screen Shot 2021-07-17 at 3 03 08 PM" src="https://user-images.githubusercontent.com/6947218/126047150-c3af20b4-32e2-4c22-92ae-092647ca6988.png">

**Comment by tom95** [comment]
Hi! Hope it's fine to comment on the closed issue but I think it concerns the same issue I would like to address.

I noticed that the auth cookie is set with remember=false https://github.com/tarecord/sign-in-with-google/blob/1aa96d7ad1777992f73bce16968ff04f44287d65/src/admin/class-sign-in-with-google-admin.php#L538

This has the effect that each time I re-open my browser I am brought back to the login page. You mentioned that Google should keep users logged in, I don't see yet how that would work but maybe I missed some piece of configuration?

For my specific use case it would be perfect to have remember=true as a plugin preference, rather than a user preference.

**Comment by BenJamesAndo** [comment]
@tom95 I was going to mention this as well. I wasn't sure if I was the only one experiencing this. I've even tried with the WordPress Persistent Login plugin but that didn't help, although it probably doesn't handle OAuth. Did you figure anyway to have it as remember=true ?

**Comment by tom95** [comment]
Hi @BenJamesAndo I ended up modifying the file and re-patching as updates come in. The exact line and file can be seen in my post above :)

Change would be:
```php
wp_set_auth_cookie( $connected_user->ID, true );
```

**Comment by BenJamesAndo** [comment]
Epic thank you @tom95 It works great now.
